#!/bin/bash
# Generate simple placeholder icons using base64 PNG data
# These are minimal blue squares - replace with proper icons later

# 16x16 blue PNG
echo "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAMklEQVQ4T2NkYGD4z0ABYBzVQBcN/ykwAd0M+D8KBgYMDAGDAowMDAwUuyEYNYwaBkQBAH8iBhEZJJETAAAAAElFTkSuQmCC" | base64 -d > icon16.png

# 48x48 blue PNG  
echo "iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAAQklEQVRoQ+3OQREAAAjDMNRf/AUPwAFJrOy2c7vnfJ3n+/uCAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAIF/BV6NBDAx+4gVfwAAAABJRU5ErkJggg==" | base64 -d > icon48.png

# 128x128 blue PNG
echo "iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAS0lEQVR42u3BAQ0AAADCoPdPbQ8HFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8GXrwAAHF3cPyAAAAAElFTkSuQmCC" | base64 -d > icon128.png

echo "Icons created!"
